export const APP = {
    MOBILE_MENU_SHOW: 'MOBILE_MENU_SHOW',
    MOBILE_MENU_HIDE: 'MOBILE_MENU_HIDE',
    MESSAGE_POPUP: 'MESSAGE_POPUP',
    ALERT_MESSAGE: 'ALERT_MESSAGE',
    ALERT_REMOVE: 'ALERT_REMOVE',
    ZOOM_IMAGE: 'ZOOM_IMAGE',
    TAB_SELECT: 'TAB_SELECT',
    SET_CITIES: 'SET_CITIES',
    SET_EYE_COLORS: 'SET_EYE_COLORS',
    SET_HAIR_COLORS: 'SET_HAIR_COLORS',
    SET_GOALS: 'SET_GOALS',
    SET_PLANS: 'SET_PLANS',
    ACCESS_SHOW: 'ACCESS_SHOW',
    ACCESS_HIDE: 'ACCESS_HIDE',
}
export const AUTH = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    FORGOT_PASSWORD: 'FORGOT_PASSWORD',
}
export const ACCOUNT = {
    SET: 'SET',
    ACTIVATE: 'ACTIVATE',
    DEACTIVATE: 'DEACTIVATE',
    UPDATE_CITY: 'UPDATE_CITY',
    UPDATE_AGE: 'UPDATE_AGE',
    UPDATE_NICKNAME: 'UPDATE_NICKNAME',
    UPDATE_DESCRIPTION: 'UPDATE_DESCRIPTION',
    UPDATE_HEIGHT: 'UPDATE_HEIGHT',
    UPDATE_WEIGHT: 'UPDATE_WEIGHT',
    SET_AVATAR: 'SET_AVATAR',
    SET_INVISIBLE: 'SET_INVISIBLE',
    SET_MESSAGES_COUNT: 'SET_MESSAGES_COUNT',
    GALLERY_IMAGE_ADD: 'GALLERY_IMAGE_ADD',
    GALLERY_IMAGE_REMOVE: 'GALLERY_IMAGE_REMOVE',
}
export const USERS = {
    SET_LIST: 'SET_LIST',
    SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
    SET_USER: 'SET_USER',
    CHECK_DIALOG: 'CHECK_DIALOG',
    DIALOG_INIT: 'DIALOG_INIT',
}
export const DIALOGS = {
    SET_LIST: 'SET_LIST',
    SET_DIALOG: 'SET_DIALOG',
    CLEAR_DIALOG: 'CLEAR_DIALOG',
    ADD_MESSAGE: 'ADD_MESSAGE',
    DELETE_MESSAGE: 'DELETE_MESSAGE',
    DELETE_DIALOG: 'DELETE_DIALOG',
    DIALOG_ERROR: 'DIALOG_ERROR',
}
export const PAYMENTS = {
    PAYMENT_INIT: 'PAYMENT_INIT'
}
export const ARTICLES = {
    SET_ARTICLES: 'SET_ARTICLES',
    CREATE_ARTICLE: 'CREATE_ARTICLE',
    ANSWER_ARTICLE: 'ANSWER_ARTICLE'
}
export const FILTERS = {
    SET_AGE: 'SET_AGE',
    SET_HEIGHT: 'SET_HEIGHT',
    SET_WEIGHT: 'SET_WEIGHT',
    SET_GOAL: 'SET_GOAL',
}